In [2]:
import numpy as np
import copy
import time
import pytz
import datetime
import math
import re
import os
import pandas as pd
from pandas import read_csv
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor, GradientBoostingClassifier
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from scipy import stats
# whether or not to split into train and test
split_data = True

from sklearn.linear_model import Lasso



In [69]:
def load_dataset(filename, features):
    # load the dataset as a pandas DataFrame
    data = read_csv(filename, header=None)
    dataset = data.values
    #print(dataset.shape)
    #print(dataset[:,features])
    labels = dataset[0][features]
    
    

    newDataset = dataset[:,features]
    # split into input (X) and output (y) variables
    
    #print(newDataset)

    newDataset = removeHeader(newDataset)
    
    #print(newDataset)

    X = newDataset[:, :-1]
    y = newDataset[:,-1]
    

    return X, y



"""def getTrainTest(csv, features):
    X, y = load_dataset(csv, features)
# split into train and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, shuffle=False)
    features = y
    
    return X_train, X_test, y_train, y_test"""

def removeHeader(data):
    newData = data[1:]
    return newData

def getTrainTest(dataset, labels):

    dataset = dataset.loc[:, labels]

    X = dataset.iloc[:, :-1].values
    y = dataset.iloc[:, -1].values    # split into train and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, shuffle=False)
    features = y

    return X_train, X_test, y_train, y_test

"""
    def load_dataset(filename, features):
    # load the dataset as a pandas DataFrame
    data = read_csv(filename, header=None)
    dataset = data.values
    labels = dataset[0][features]
    newDataset = dataset[:,features]
    newDataset = removeHeader(newDataset)
    
    X = newDataset[:, :-1]
    y = newDataset[:,-1]
    
    return X, y
"""



def convertLabels(dataset, features):
    labels = list(dataset)
    return labels


def predictionsRandomForest(dataset, feats):
    
    #dataset = pd.read_csv(csv)
    
    
    labels = convertLabels(dataset, feats)
    X_train, X_test, y_train, y_test = getTrainTest(dataset, labels)
    
    intPreds = []
    
    model = RandomForestRegressor()
    #model.fit(X_train, y_train)
    #y_pred = model.predict(X_test)
    
    """starts tutorial"""
    
    # Saving feature names for later use
    feature_list = list(dataset)
    # The baseline predictions are the historical averages
    baseline_preds = X_test[:,0]
    #print(baseline_preds)
    # Baseline errors, and display average baseline error
    baseline_errors = abs(baseline_preds - y_test)
    #print('Average baseline error: ', round(np.mean(baseline_errors), 2))
    #Average baseline error:  5.06 degrees.
    
    # Train the model on training data
    model.fit(X_train, y_train);
    # Use the forest's predict method on the test data
    y_pred = model.predict(X_test)
    # Calculate the absolute errors
    errors = abs(y_pred - y_test)
    # Print out the mean absolute error (mae)
    mae = round(np.mean(errors), 2)
    #print('Mean Absolute Error:', mae, 'degrees.')
    
    
    for x in y_pred:
        intPreds.append(round(x))
                
    normPred = np.linalg.norm(intPreds - np.array(y_test))
    corr = correlation(intPreds, y_test)
    return(mae, y_test)
    #return(normPred, y_test, corr)


def predictionsLinearRegression(dataset, feats):
    
    #dataset = pd.read_csv(csv)
    
    labels = convertLabels(dataset, feats)

    X_train, X_test, y_train, y_test = getTrainTest(dataset, labels)

    intPreds = []
    model = LinearRegression()
    """model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)"""
    
    #tutorial
    feature_list = list(dataset)
    baseline_preds = X_test[:,0]
    baseline_errors = abs(baseline_preds - y_test)
    
    model.fit(X_train, y_train);
    y_pred = model.predict(X_test)
    errors = abs(y_pred - y_test)
    mae = round(np.mean(errors), 2)
    
    
    for x in y_pred:
        intPreds.append(round(x))
                
    normPred = np.linalg.norm(intPreds - np.array(y_test))
    corr = correlation(intPreds, y_test)
    
    return(mae, y_test)

    #return(normPred, y_test, corr)

from sklearn import preprocessing
from sklearn import utils
def predictionsSVM(dataset, feats):
    print(feats)
    #dataset = pd.read_csv(csv)
    labels = convertLabels(dataset, feats)
    X_train, X_test, y_train, y_test = getTrainTest(dataset, labels)
    intPreds = []
    
    np.seterr(divide='ignore', invalid='ignore')

    lab_enc = preprocessing.LabelEncoder()
    encoded = lab_enc.fit_transform(y_train)
    
    model = svm.SVC()
    """model.fit(X_train, encoded)
    #model.fit(X_train, y_train)

    y_pred = model.predict(X_test)"""
    
    #tutorial
    feature_list = list(dataset)
    baseline_preds = X_test[:,0]
    baseline_errors = abs(baseline_preds - y_test)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    errors = abs(y_pred - y_test)
    mae = round(np.mean(errors), 2)
    
    for x in y_pred:
        intPreds.append(round(x))
                
    normPred = np.linalg.norm(intPreds - np.array(y_test))
    corr = correlation(intPreds, y_test)
    
    return(mae, y_test)

    #return(normPred, y_test, corr)


def predictionsLASSO(dataset, feats):
    
    #dataset = pd.read_csv(csv)
    labels = convertLabels(dataset, feats)
    X_train, X_test, y_train, y_test = getTrainTest(dataset, labels)
    intPreds = []
    
    model = Lasso(alpha=1.0)
    """model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)"""
    
    
    #tutorial
    feature_list = list(dataset)
    baseline_preds = X_test[:,0]
    baseline_errors = abs(baseline_preds - y_test)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    errors = abs(y_pred - y_test)
    mae = round(np.mean(errors), 2)
    
    
    for x in y_pred:
        intPreds.append(round(x))
                
    normPred = np.linalg.norm(intPreds - np.array(y_test))
    corr = correlation(intPreds, y_test)
    #return(normPred, y_test, corr)
    return(mae, y_test)

from sklearn.datasets import make_classification
from sklearn.ensemble import GradientBoostingClassifier

def predictionsGradientBoostingClassifier(dataset, feats):
    
    
    #dataset = pd.read_csv(csv)
    
    labels = convertLabels(dataset, feats)
    X_train, X_test, y_train, y_test = getTrainTest(dataset, labels)
    
    intPreds = []
    
    lab_enc = preprocessing.LabelEncoder()
    encoded = lab_enc.fit_transform(y_train)
    
    model = GradientBoostingClassifier()
    model.fit(X_train, encoded)
    
    y_pred = model.predict(X_test)
    
    for x in y_pred:
        intPreds.append(round(x))
                
    normPred = np.linalg.norm(intPreds - np.array(y_test))
    corr = correlation(intPreds, y_test)
    return(normPred, y_test, corr)
    
    
#def bestPred(features, predictions, numFeatsToRem):
    

def remWorstFeat(features, predictions, numFeatsToRem):
    worst = 0
    length = len(predictions)
    assert(len(features)==len(predictions))
        
    for x in range(numFeatsToRem):
        worst = 0 #index of worst feature
        for y in range(length):
            if(predictions[y] > predictions[worst]):
                worst = y
        
        if (length > 1):
            #print(predictions, predictions[worst])
            #print(features, features[worst])
        
            del predictions[worst]
            del features[worst]
        length = length - 1
    return features

    
import seaborn as sns
import matplotlib.pyplot as plt


def correlation(y_pred, y_test):
    covariance = np.cov(y_pred, y_test)
    pred = ['y_pred', 'y_test']
    
    correlation = np.corrcoef(y_pred, y_test)
    return(correlation[0][1])


def correlationArray(correlation):
    return correlation[0][1]
    
import copy
def bestFeatsFirstCopy(dataset, feats, model):
    featurePred=[]
    featureCorrs=[]
    
    sublength = len(feats) #length of feature list post removal
    featsCopy = copy.deepcopy(feats) # array of features post removal
    featSubset = copy.deepcopy(feats) #for loop feature (remove one at a time)
    allCorrIters = [] #append each array, removing one at a time
    

    run = 0
    #without while loop (one iteration)
    """for x in range(length-1):
        featsCopy = featsCopy[:x] + featsCopy[(x+1):]
        predict = predictions(csv, featsCopy)
        featurePred.append(predict[0])
        featureCorrs.append(predict[2])
        featsCopy = []
        featsCopy = feats   """
        
    #with while loop (many iterations to find best)
    #while sublength != 2: #2 best features
    assert(sublength > 10)
    
    while sublength != 10: #10 best features
        for x in range(len(featsCopy) - 1):
            featSubset = featSubset[:x] + featSubset[(x+1):]
            if(model == 'RandomForest'):
                predict = predictionsRandomForest(csv, featSubset)
            elif(model == 'LinearRegression'):
                predict = predictionsLinearRegression(csv, featSubset)
            elif(model == 'SVM'):
                predict = predictionsSVM(csv, featSubset)
            elif(model == 'LASSO'):
                predict = predictionsLASSO(csv, featSubset)
            elif(model == 'GradientBoostingClassifier'):
                predict = predictionsGradientBoostingClassifier(csv, featSubset)
            #featurePred.append(predict[0])
            featureCorrs.append(predict[2])
            featSubset = copy.deepcopy(featsCopy)
            
        run = run + 1
        print("run = ")
        print(run)
        #print(featureCorrs)
        allCorrIters.append(featureCorrs)
        if sublength >= 50:
            featsCopy = remWorstFeat(featsCopy[:-1], featureCorrs, 50)
        else:
            featsCopy = remWorstFeat(featsCopy[:-1], featureCorrs, 1)
        #remWorstFeat should return feature list
        sublength = len(featsCopy)
        featSubset = copy.deepcopy(featsCopy)
        featureCorrs = []
        
    
    
    featureCorrs = allCorrIters[-1]
    print(featureCorrs)
    
    """print("Prediction")
    print(featurePred)
    print(predict[1])"""

    #featurePred shows the prediction if this feature was removed. If score is low, this means prediction would be lower if this was removed
    
    """ L = [ (featurePred[i],i) for i in range(len(featurePred)) ]
    L.sort()
    sorted_l,permutationL = zip(*L)
    permutationNpL = np.array(permutationL)
    print(permutationNpL)
    print(convertLabels(csv, permutationNpL))"""
    #featureCorrs shows the prediction if this feature was removed. If score is low, this means prediction would be lower if this was removed

    
    
    print("Correlation")
    print(featureCorrs)

    N = [ (featureCorrs[j],j) for j in range(len(featureCorrs)) ]
    N.sort()
    sorted_n,permutationN = zip(*N)
    permutationNpN = np.array(permutationN)
        
    print(permutationNpN)
    print(convertLabels(csv, permutationNpN))

    #featurePred = np.array(featurePred)
    featureCorrs = np.array(featureCorrs)

    corrVar = np.var(featureCorrs)
    print("variance: ", corrVar)
    
    #return permutationNpL, permutationNpN
    #return permutationNpN
    return corrVar

In [10]:
#features = createList(384)

def createList(n):
    lst = []
    for i in range(n):
        lst.append(i)
    return(lst)


mirnaVars = []
mrnaVars = []
protVars = []

datasetMirna = pd.read_csv('/Users/soniasharapova/Documents/MultiOmics/mirnaCategorical.csv')
datasetMrna = pd.read_csv('/Users/soniasharapova/Documents/MultiOmics/mrnaCategorical.csv')
datasetProt = pd.read_csv('/Users/soniasharapova/Documents/MultiOmics/protCategorical.csv')


# Random Forest

In [96]:
mirnaFeatures = createList(184)
#dataset = pd.read_csv('/Users/soniasharapova/Documents/MultiOmics/mirnaCategorical.csv')
print(mirnaFeatures)
mirnaRandomForestVar = bestFeats(datasetMirna, mirnaFeatures, 'RandomForest')[1]
#mirnaRandomForestVar = bestFeats('/Users/soniasharapova/Documents/MultiOmics/mirnaCategorical.csv', mirnaFeatures, 'RandomForest')
mirnaVars.append(['RandomForest', mirnaRandomForestVar])
print("-------------")

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183]
run 2
run 3
run 4
run 5
run 6
run 7
run 8
run 9
run 10
run 11
[183, 0, 158, 5, 23, 59, 11, 10, 92, 126]
[0.0, 0.33, 0.35, 0.35, 0.36, 0.36, 0.36, 0.35, 0.33, 0.35]
-------------


In [97]:
mrnaFeatures = createList(200)
#datasetMrna = pd.read_csv('/Users/soniasharapova/Documents/MultiOmics/mrnaCategorical.csv')

mrnaRandomForestVar = bestFeats(datasetMrna, mrnaFeatures, 'RandomForest')[1]
mrnaVars.append(['RandomForest', mrnaRandomForestVar])
print(mrnaRandomForestVar)
print("-------------")

run 2
run 3
run 4
run 5
run 6
run 7
run 8
run 9
run 10
run 11
[199, 19, 120, 8, 122, 36, 23, 25, 1, 24]
[1.5e-323, 0.21, 0.23, 0.21, 0.23, 0.23, 0.23, 0.22, 0.21, 0.23]
[1.5e-323, 0.21, 0.23, 0.21, 0.23, 0.23, 0.23, 0.22, 0.21, 0.23]
-------------


In [98]:
protFeatures = createList(142)
#datasetProt = pd.read_csv('/Users/soniasharapova/Documents/MultiOmics/protCategorical.csv')

protRandomForestVar = bestFeats(datasetProt, protFeatures, 'RandomForest')[1]
protVars.append(['RandomForest', protRandomForestVar])

print(protRandomForestVar)
print("-------------")

run 2
run 3
run 4
run 5
run 6
run 7
run 8
run 9
run 10
run 11
[141, 24, 124, 3, 14, 101, 118, 77, 28, 120]
[5.04e-322, 0.29, 0.35, 0.3, 0.34, 0.31, 0.32, 0.32, 0.34, 0.31]
[5.04e-322, 0.29, 0.35, 0.3, 0.34, 0.31, 0.32, 0.32, 0.34, 0.31]
-------------


# Linear Regression

In [87]:
mirnaFeatures = createList(184)

mirnaLinearRegressionVar = bestFeats(datasetMirna, mirnaFeatures, 'LinearRegression')[1]
mirnaVars.append(['LinearRegression', mirnaLinearRegressionVar])

print(mirnaLinearRegressionVar)
print("-------------")

run 2
run 3
run 4
run 5
run 6
run 7
run 8
run 9
run 10
run 11
[183, 0, 2, 3, 4, 5, 6, 7, 8, 9]
[-0.21054475042809756, 0.85, 0.85, 0.85, 0.85, 0.85, 0.85, 0.85, 0.85, 0.85]
[-0.21054475042809756, 0.85, 0.85, 0.85, 0.85, 0.85, 0.85, 0.85, 0.85, 0.85]
-------------


In [88]:
mrnaFeatures = createList(200)
mrnaLinearRegressionVar = bestFeats(datasetMrna, mrnaFeatures, 'LinearRegression')[1]
mrnaVars.append(['LinearRegression', mrnaLinearRegressionVar])

print(mrnaLinearRegressionVar)
print("-------------")

run 2
run 3
run 4
run 5
run 6
run 7
run 8
run 9
run 10
run 11
[199, 0, 2, 3, 4, 5, 6, 7, 8, 9]
[1.5e-323, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48]
[1.5e-323, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48]
-------------


In [89]:
protFeatures = createList(142)
protLinearRegressionVar = bestFeats(datasetProt, protFeatures, 'LinearRegression')[1]
protVars.append(['LinearRegression', protLinearRegressionVar])

print(protLinearRegressionVar)
print("-------------")

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

run 2


/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

run 3


/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

run 4


/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

run 5


/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

run 6


/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

run 7


/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

run 8


/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

run 9


/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

run 10


/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

run 11
[0, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48]
[0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48]
-------------


/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/soniasharapova/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encoun

# SVM

In [90]:
from sklearn import svm

mirnaFeatures = createList(184)

mirnaSVMVar = bestFeats(datasetMirna, mirnaFeatures, 'SVM')[1]
mirnaVars.append(['SVM', mirnaSVMVar])

print(mirnaSVMVar)
print("-------------")

[0]
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]
[10]
[11]
[12]
[13]
[14]
[15]
[16]
[17]
[18]
[19]
[20]
[21]
[22]
[23]
[24]
[25]
[26]
[27]
[28]
[29]
[30]
[31]
[32]
[33]
[34]
[35]
[36]
[37]
[38]
[39]
[40]
[41]
[42]
[43]
[44]
[45]
[46]
[47]
[48]
[49]
[50]
[51]
[52]
[53]
[54]
[55]
[56]
[57]
[58]
[59]
[60]
[61]
[62]
[63]
[64]
[65]
[66]
[67]
[68]
[69]
[70]
[71]
[72]
[73]
[74]
[75]
[76]
[77]
[78]
[79]
[80]
[81]
[82]
[83]
[84]
[85]
[86]
[87]
[88]
[89]
[90]
[91]
[92]
[93]
[94]
[95]
[96]
[97]
[98]
[99]
[100]
[101]
[102]
[103]
[104]
[105]
[106]
[107]
[108]
[109]
[110]
[111]
[112]
[113]
[114]
[115]
[116]
[117]
[118]
[119]
[120]
[121]
[122]
[123]
[124]
[125]
[126]
[127]
[128]
[129]
[130]
[131]
[132]
[133]
[134]
[135]
[136]
[137]
[138]
[139]
[140]
[141]
[142]
[143]
[144]
[145]
[146]
[147]
[148]
[149]
[150]
[151]
[152]
[153]
[154]
[155]
[156]
[157]
[158]
[159]
[160]
[161]
[162]
[163]
[164]
[165]
[166]
[167]
[168]
[169]
[170]
[171]
[172]
[173]
[174]
[175]
[176]
[177]
[178]
[179]
[180]
[181]
[182]
run 2
[183  

[183   0   2 173]
[183   0   2 174]
[183   0   2 175]
[183   0   2 176]
[183   0   2 177]
[183   0   2 178]
[183   0   2 179]
[183   0   2 180]
[183   0   2 181]
run 5
[183   0   2   3   1]
[183   0   2   3   4]
[183   0   2   3   5]
[183   0   2   3   6]
[183   0   2   3   7]
[183   0   2   3   8]
[183   0   2   3   9]
[183   0   2   3  10]
[183   0   2   3  11]
[183   0   2   3  12]
[183   0   2   3  13]
[183   0   2   3  14]
[183   0   2   3  15]
[183   0   2   3  16]
[183   0   2   3  17]
[183   0   2   3  18]
[183   0   2   3  19]
[183   0   2   3  20]
[183   0   2   3  21]
[183   0   2   3  22]
[183   0   2   3  23]
[183   0   2   3  24]
[183   0   2   3  25]
[183   0   2   3  26]
[183   0   2   3  27]
[183   0   2   3  28]
[183   0   2   3  29]
[183   0   2   3  30]
[183   0   2   3  31]
[183   0   2   3  32]
[183   0   2   3  33]
[183   0   2   3  34]
[183   0   2   3  35]
[183   0   2   3  36]
[183   0   2   3  37]
[183   0   2   3  38]
[183   0   2   3  39]
[183   0   2   3  

[183   0   2   3   4 163]
[183   0   2   3   4 164]
[183   0   2   3   4 165]
[183   0   2   3   4 166]
[183   0   2   3   4 167]
[183   0   2   3   4 168]
[183   0   2   3   4 169]
[183   0   2   3   4 170]
[183   0   2   3   4 171]
[183   0   2   3   4 172]
[183   0   2   3   4 173]
[183   0   2   3   4 174]
[183   0   2   3   4 175]
[183   0   2   3   4 176]
[183   0   2   3   4 177]
[183   0   2   3   4 178]
[183   0   2   3   4 179]
[183   0   2   3   4 180]
[183   0   2   3   4 181]
run 7
[183   0   2   3   4   5   1]
[183   0   2   3   4   5   6]
[183   0   2   3   4   5   7]
[183   0   2   3   4   5   8]
[183   0   2   3   4   5   9]
[183   0   2   3   4   5  10]
[183   0   2   3   4   5  11]
[183   0   2   3   4   5  12]
[183   0   2   3   4   5  13]
[183   0   2   3   4   5  14]
[183   0   2   3   4   5  15]
[183   0   2   3   4   5  16]
[183   0   2   3   4   5  17]
[183   0   2   3   4   5  18]
[183   0   2   3   4   5  19]
[183   0   2   3   4   5  20]
[183   0   2   3   4

[183   0   2   3   4   5   6  80]
[183   0   2   3   4   5   6  81]
[183   0   2   3   4   5   6  82]
[183   0   2   3   4   5   6  83]
[183   0   2   3   4   5   6  84]
[183   0   2   3   4   5   6  85]
[183   0   2   3   4   5   6  86]
[183   0   2   3   4   5   6  87]
[183   0   2   3   4   5   6  88]
[183   0   2   3   4   5   6  89]
[183   0   2   3   4   5   6  90]
[183   0   2   3   4   5   6  91]
[183   0   2   3   4   5   6  92]
[183   0   2   3   4   5   6  93]
[183   0   2   3   4   5   6  94]
[183   0   2   3   4   5   6  95]
[183   0   2   3   4   5   6  96]
[183   0   2   3   4   5   6  97]
[183   0   2   3   4   5   6  98]
[183   0   2   3   4   5   6  99]
[183   0   2   3   4   5   6 100]
[183   0   2   3   4   5   6 101]
[183   0   2   3   4   5   6 102]
[183   0   2   3   4   5   6 103]
[183   0   2   3   4   5   6 104]
[183   0   2   3   4   5   6 105]
[183   0   2   3   4   5   6 106]
[183   0   2   3   4   5   6 107]
[183   0   2   3   4   5   6 108]
[183   0   2  

[183   0   2   3   4   5   6   7 160]
[183   0   2   3   4   5   6   7 161]
[183   0   2   3   4   5   6   7 162]
[183   0   2   3   4   5   6   7 163]
[183   0   2   3   4   5   6   7 164]
[183   0   2   3   4   5   6   7 165]
[183   0   2   3   4   5   6   7 166]
[183   0   2   3   4   5   6   7 167]
[183   0   2   3   4   5   6   7 168]
[183   0   2   3   4   5   6   7 169]
[183   0   2   3   4   5   6   7 170]
[183   0   2   3   4   5   6   7 171]
[183   0   2   3   4   5   6   7 172]
[183   0   2   3   4   5   6   7 173]
[183   0   2   3   4   5   6   7 174]
[183   0   2   3   4   5   6   7 175]
[183   0   2   3   4   5   6   7 176]
[183   0   2   3   4   5   6   7 177]
[183   0   2   3   4   5   6   7 178]
[183   0   2   3   4   5   6   7 179]
[183   0   2   3   4   5   6   7 180]
[183   0   2   3   4   5   6   7 181]
run 10
[183   0   2   3   4   5   6   7   8   1]
[183   0   2   3   4   5   6   7   8   9]
[183   0   2   3   4   5   6   7   8  10]
[183   0   2   3   4   5   6   

In [91]:
mrnaFeatures = createList(200)
mrnaSVMVar = bestFeats(datasetMrna, mrnaFeatures, 'SVM')[1]
mrnaVars.append(['SVM', mrnaSVMVar])

print(mrnaSVMVar)
print("-------------")

[0]
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]
[10]
[11]
[12]
[13]
[14]
[15]
[16]
[17]
[18]
[19]
[20]
[21]
[22]
[23]
[24]
[25]
[26]
[27]
[28]
[29]
[30]
[31]
[32]
[33]
[34]
[35]
[36]
[37]
[38]
[39]
[40]
[41]
[42]
[43]
[44]
[45]
[46]
[47]
[48]
[49]
[50]
[51]
[52]
[53]
[54]
[55]
[56]
[57]
[58]
[59]
[60]
[61]
[62]
[63]
[64]
[65]
[66]
[67]
[68]
[69]
[70]
[71]
[72]
[73]
[74]
[75]
[76]
[77]
[78]
[79]
[80]
[81]
[82]
[83]
[84]
[85]
[86]
[87]
[88]
[89]
[90]
[91]
[92]
[93]
[94]
[95]
[96]
[97]
[98]
[99]
[100]
[101]
[102]
[103]
[104]
[105]
[106]
[107]
[108]
[109]
[110]
[111]
[112]
[113]
[114]
[115]
[116]
[117]
[118]
[119]
[120]
[121]
[122]
[123]
[124]
[125]
[126]
[127]
[128]
[129]
[130]
[131]
[132]
[133]
[134]
[135]
[136]
[137]
[138]
[139]
[140]
[141]
[142]
[143]
[144]
[145]
[146]
[147]
[148]
[149]
[150]
[151]
[152]
[153]
[154]
[155]
[156]
[157]
[158]
[159]
[160]
[161]
[162]
[163]
[164]
[165]
[166]
[167]
[168]
[169]
[170]
[171]
[172]
[173]
[174]
[175]
[176]
[177]
[178]
[179]
[180]
[181]
[182]
[183]
[184]


[199   0   2 151]
[199   0   2 152]
[199   0   2 153]
[199   0   2 154]
[199   0   2 155]
[199   0   2 156]
[199   0   2 157]
[199   0   2 158]
[199   0   2 159]
[199   0   2 160]
[199   0   2 161]
[199   0   2 162]
[199   0   2 163]
[199   0   2 164]
[199   0   2 165]
[199   0   2 166]
[199   0   2 167]
[199   0   2 168]
[199   0   2 169]
[199   0   2 170]
[199   0   2 171]
[199   0   2 172]
[199   0   2 173]
[199   0   2 174]
[199   0   2 175]
[199   0   2 176]
[199   0   2 177]
[199   0   2 178]
[199   0   2 179]
[199   0   2 180]
[199   0   2 181]
[199   0   2 182]
[199   0   2 183]
[199   0   2 184]
[199   0   2 185]
[199   0   2 186]
[199   0   2 187]
[199   0   2 188]
[199   0   2 189]
[199   0   2 190]
[199   0   2 191]
[199   0   2 192]
[199   0   2 193]
[199   0   2 194]
[199   0   2 195]
[199   0   2 196]
[199   0   2 197]
run 5
[199   0   2   3   1]
[199   0   2   3   4]
[199   0   2   3   5]
[199   0   2   3   6]
[199   0   2   3   7]
[199   0   2   3   8]
[199   0   2   3

[199   0   2   3   4 145]
[199   0   2   3   4 146]
[199   0   2   3   4 147]
[199   0   2   3   4 148]
[199   0   2   3   4 149]
[199   0   2   3   4 150]
[199   0   2   3   4 151]
[199   0   2   3   4 152]
[199   0   2   3   4 153]
[199   0   2   3   4 154]
[199   0   2   3   4 155]
[199   0   2   3   4 156]
[199   0   2   3   4 157]
[199   0   2   3   4 158]
[199   0   2   3   4 159]
[199   0   2   3   4 160]
[199   0   2   3   4 161]
[199   0   2   3   4 162]
[199   0   2   3   4 163]
[199   0   2   3   4 164]
[199   0   2   3   4 165]
[199   0   2   3   4 166]
[199   0   2   3   4 167]
[199   0   2   3   4 168]
[199   0   2   3   4 169]
[199   0   2   3   4 170]
[199   0   2   3   4 171]
[199   0   2   3   4 172]
[199   0   2   3   4 173]
[199   0   2   3   4 174]
[199   0   2   3   4 175]
[199   0   2   3   4 176]
[199   0   2   3   4 177]
[199   0   2   3   4 178]
[199   0   2   3   4 179]
[199   0   2   3   4 180]
[199   0   2   3   4 181]
[199   0   2   3   4 182]
[199   0   2

[199   0   2   3   4   5   6  72]
[199   0   2   3   4   5   6  73]
[199   0   2   3   4   5   6  74]
[199   0   2   3   4   5   6  75]
[199   0   2   3   4   5   6  76]
[199   0   2   3   4   5   6  77]
[199   0   2   3   4   5   6  78]
[199   0   2   3   4   5   6  79]
[199   0   2   3   4   5   6  80]
[199   0   2   3   4   5   6  81]
[199   0   2   3   4   5   6  82]
[199   0   2   3   4   5   6  83]
[199   0   2   3   4   5   6  84]
[199   0   2   3   4   5   6  85]
[199   0   2   3   4   5   6  86]
[199   0   2   3   4   5   6  87]
[199   0   2   3   4   5   6  88]
[199   0   2   3   4   5   6  89]
[199   0   2   3   4   5   6  90]
[199   0   2   3   4   5   6  91]
[199   0   2   3   4   5   6  92]
[199   0   2   3   4   5   6  93]
[199   0   2   3   4   5   6  94]
[199   0   2   3   4   5   6  95]
[199   0   2   3   4   5   6  96]
[199   0   2   3   4   5   6  97]
[199   0   2   3   4   5   6  98]
[199   0   2   3   4   5   6  99]
[199   0   2   3   4   5   6 100]
[199   0   2  

[199   0   2   3   4   5   6   7 118]
[199   0   2   3   4   5   6   7 119]
[199   0   2   3   4   5   6   7 120]
[199   0   2   3   4   5   6   7 121]
[199   0   2   3   4   5   6   7 122]
[199   0   2   3   4   5   6   7 123]
[199   0   2   3   4   5   6   7 124]
[199   0   2   3   4   5   6   7 125]
[199   0   2   3   4   5   6   7 126]
[199   0   2   3   4   5   6   7 127]
[199   0   2   3   4   5   6   7 128]
[199   0   2   3   4   5   6   7 129]
[199   0   2   3   4   5   6   7 130]
[199   0   2   3   4   5   6   7 131]
[199   0   2   3   4   5   6   7 132]
[199   0   2   3   4   5   6   7 133]
[199   0   2   3   4   5   6   7 134]
[199   0   2   3   4   5   6   7 135]
[199   0   2   3   4   5   6   7 136]
[199   0   2   3   4   5   6   7 137]
[199   0   2   3   4   5   6   7 138]
[199   0   2   3   4   5   6   7 139]
[199   0   2   3   4   5   6   7 140]
[199   0   2   3   4   5   6   7 141]
[199   0   2   3   4   5   6   7 142]
[199   0   2   3   4   5   6   7 143]
[199   0   2

[199   0   2   3   4   5   6   7   8 164]
[199   0   2   3   4   5   6   7   8 165]
[199   0   2   3   4   5   6   7   8 166]
[199   0   2   3   4   5   6   7   8 167]
[199   0   2   3   4   5   6   7   8 168]
[199   0   2   3   4   5   6   7   8 169]
[199   0   2   3   4   5   6   7   8 170]
[199   0   2   3   4   5   6   7   8 171]
[199   0   2   3   4   5   6   7   8 172]
[199   0   2   3   4   5   6   7   8 173]
[199   0   2   3   4   5   6   7   8 174]
[199   0   2   3   4   5   6   7   8 175]
[199   0   2   3   4   5   6   7   8 176]
[199   0   2   3   4   5   6   7   8 177]
[199   0   2   3   4   5   6   7   8 178]
[199   0   2   3   4   5   6   7   8 179]
[199   0   2   3   4   5   6   7   8 180]
[199   0   2   3   4   5   6   7   8 181]
[199   0   2   3   4   5   6   7   8 182]
[199   0   2   3   4   5   6   7   8 183]
[199   0   2   3   4   5   6   7   8 184]
[199   0   2   3   4   5   6   7   8 185]
[199   0   2   3   4   5   6   7   8 186]
[199   0   2   3   4   5   6   7  

In [92]:
protFeatures = createList(142)
protSVMVar = bestFeats(datasetProt, protFeatures, 'SVM')[1]
protVars.append(['SVM', protSVMVar])

print(protSVMVar)
print("-------------")

[0]
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]
[10]
[11]
[12]
[13]
[14]
[15]
[16]
[17]
[18]
[19]
[20]
[21]
[22]
[23]
[24]
[25]
[26]
[27]
[28]
[29]
[30]
[31]
[32]
[33]
[34]
[35]
[36]
[37]
[38]
[39]
[40]
[41]
[42]
[43]
[44]
[45]
[46]
[47]
[48]
[49]
[50]
[51]
[52]
[53]
[54]
[55]
[56]
[57]
[58]
[59]
[60]
[61]
[62]
[63]
[64]
[65]
[66]
[67]
[68]
[69]
[70]
[71]
[72]
[73]
[74]
[75]
[76]
[77]
[78]
[79]
[80]
[81]
[82]
[83]
[84]
[85]
[86]
[87]
[88]
[89]
[90]
[91]
[92]
[93]
[94]
[95]
[96]
[97]
[98]
[99]
[100]
[101]
[102]
[103]
[104]
[105]
[106]
[107]
[108]
[109]
[110]
[111]
[112]
[113]
[114]
[115]
[116]
[117]
[118]
[119]
[120]
[121]
[122]
[123]
[124]
[125]
[126]
[127]
[128]
[129]
[130]
[131]
[132]
[133]
[134]
[135]
[136]
[137]
[138]
[139]
[140]
run 2
[0 1]
[0 2]
[0 3]
[0 4]
[0 5]
[0 6]
[0 7]
[0 8]
[0 9]
[ 0 10]
[ 0 11]
[ 0 12]
[ 0 13]
[ 0 14]
[ 0 15]
[ 0 16]
[ 0 17]
[ 0 18]
[ 0 19]
[ 0 20]
[ 0 21]
[ 0 22]
[ 0 23]
[ 0 24]
[ 0 25]
[ 0 26]
[ 0 27]
[ 0 28]
[ 0 29]
[ 0 30]
[ 0 31]
[ 0 32]
[ 0 33]
[ 0 34]
[ 0 

[ 0  2  3  4  5 52]
[ 0  2  3  4  5 53]
[ 0  2  3  4  5 54]
[ 0  2  3  4  5 55]
[ 0  2  3  4  5 56]
[ 0  2  3  4  5 57]
[ 0  2  3  4  5 58]
[ 0  2  3  4  5 59]
[ 0  2  3  4  5 60]
[ 0  2  3  4  5 61]
[ 0  2  3  4  5 62]
[ 0  2  3  4  5 63]
[ 0  2  3  4  5 64]
[ 0  2  3  4  5 65]
[ 0  2  3  4  5 66]
[ 0  2  3  4  5 67]
[ 0  2  3  4  5 68]
[ 0  2  3  4  5 69]
[ 0  2  3  4  5 70]
[ 0  2  3  4  5 71]
[ 0  2  3  4  5 72]
[ 0  2  3  4  5 73]
[ 0  2  3  4  5 74]
[ 0  2  3  4  5 75]
[ 0  2  3  4  5 76]
[ 0  2  3  4  5 77]
[ 0  2  3  4  5 78]
[ 0  2  3  4  5 79]
[ 0  2  3  4  5 80]
[ 0  2  3  4  5 81]
[ 0  2  3  4  5 82]
[ 0  2  3  4  5 83]
[ 0  2  3  4  5 84]
[ 0  2  3  4  5 85]
[ 0  2  3  4  5 86]
[ 0  2  3  4  5 87]
[ 0  2  3  4  5 88]
[ 0  2  3  4  5 89]
[ 0  2  3  4  5 90]
[ 0  2  3  4  5 91]
[ 0  2  3  4  5 92]
[ 0  2  3  4  5 93]
[ 0  2  3  4  5 94]
[ 0  2  3  4  5 95]
[ 0  2  3  4  5 96]
[ 0  2  3  4  5 97]
[ 0  2  3  4  5 98]
[ 0  2  3  4  5 99]
[  0   2   3   4   5 100]
[  0   2   3  

[ 0  2  3  4  5  6  7  8 22]
[ 0  2  3  4  5  6  7  8 23]
[ 0  2  3  4  5  6  7  8 24]
[ 0  2  3  4  5  6  7  8 25]
[ 0  2  3  4  5  6  7  8 26]
[ 0  2  3  4  5  6  7  8 27]
[ 0  2  3  4  5  6  7  8 28]
[ 0  2  3  4  5  6  7  8 29]
[ 0  2  3  4  5  6  7  8 30]
[ 0  2  3  4  5  6  7  8 31]
[ 0  2  3  4  5  6  7  8 32]
[ 0  2  3  4  5  6  7  8 33]
[ 0  2  3  4  5  6  7  8 34]
[ 0  2  3  4  5  6  7  8 35]
[ 0  2  3  4  5  6  7  8 36]
[ 0  2  3  4  5  6  7  8 37]
[ 0  2  3  4  5  6  7  8 38]
[ 0  2  3  4  5  6  7  8 39]
[ 0  2  3  4  5  6  7  8 40]
[ 0  2  3  4  5  6  7  8 41]
[ 0  2  3  4  5  6  7  8 42]
[ 0  2  3  4  5  6  7  8 43]
[ 0  2  3  4  5  6  7  8 44]
[ 0  2  3  4  5  6  7  8 45]
[ 0  2  3  4  5  6  7  8 46]
[ 0  2  3  4  5  6  7  8 47]
[ 0  2  3  4  5  6  7  8 48]
[ 0  2  3  4  5  6  7  8 49]
[ 0  2  3  4  5  6  7  8 50]
[ 0  2  3  4  5  6  7  8 51]
[ 0  2  3  4  5  6  7  8 52]
[ 0  2  3  4  5  6  7  8 53]
[ 0  2  3  4  5  6  7  8 54]
[ 0  2  3  4  5  6  7  8 55]
[ 0  2  3  4  

# LASSO

In [93]:
mirnaFeatures = createList(184)

mirnaLASSOVar = bestFeats(datasetMirna, mirnaFeatures, 'LASSO')[1]
mirnaVars.append(['LASSO', mirnaLASSOVar])

print(mirnaLASSOVar)
print("-------------")

run 2
run 3
run 4
run 5
run 6
run 7
run 8
run 9
run 10
run 11
[183, 0, 2, 3, 4, 5, 6, 7, 8, 9]
[0.0, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74]
[0.0, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74]
-------------


In [94]:
mrnaFeatures = createList(200)
mrnaLASSOVar = bestFeats(datasetMrna, mrnaFeatures, 'LASSO')[1]
mrnaVars.append(['LASSO', mrnaLASSOVar])

print(mrnaLASSOVar)
print("-------------")

run 2
run 3
run 4
run 5
run 6
run 7
run 8
run 9
run 10
run 11
[199, 0, 2, 3, 4, 5, 6, 7, 8, 9]
[1.5e-323, 0.71, 0.71, 0.71, 0.71, 0.71, 0.71, 0.71, 0.71, 0.71]
[1.5e-323, 0.71, 0.71, 0.71, 0.71, 0.71, 0.71, 0.71, 0.71, 0.71]
-------------


In [95]:
protFeatures = createList(142)
protLASSOVar = bestFeats(datasetProt, protFeatures, 'LASSO')[1]
protVars.append(['LASSO', protLASSOVar])

print(protLASSOVar)
print("-------------")

run 2
run 3
run 4
run 5
run 6
run 7
run 8
run 9
run 10
run 11
[0, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98]
[0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98]
-------------


# Gradient Boosting

In [ ]:

mirnaFeatures = createList(184)

mirnaGradientBoostingVar = bestFeats(dataset, mirnaFeatures, 'GradientBoostingClassifier')
mirnaVars.append(['GradientBoosting', mirnaGradientBoostingVar])

print(mirnaGradientBoostingVar)
print("-------------")

# Vectors

In [ ]:
# create vector for each gene (for each modality and model):
# (modality x model = 3 x 4 = 12)
# g -> {r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12}
# where r1 = random forest+mirna
# r2 = line regression + mirna

In [21]:
# have a performance ranking of each model for each module in vector form
#we have 4 (maybe add one) models, so create 3 vectors, each with 4 ranks.

#best to worst

#mirna <- [1, 2, 3, 4]
#mrna <- [1, 2, 3, 4]
#prot <- [1, 2, 3, 4]

import operator

dummyList = [['A', 0.0004],['B', 0.00007],['C', 0.001],['D', 0.1], ['E', 0.009]]

def getKeyaValues(array):
    keys = []
    values = []
    
    for x in array:
        keys.append(x[0])
        values.append(x[1])
    
    return(keys, values)

def vector(keys, values):  

    print ("Original key list is : " + str(keys))
    print ("Original value list is : " + str(values))

    zipped = zip(keys, values)
    res = (dict(zipped))

    print ("Resultant dictionary is : " + str(res))

    sortedVector = sorted(res.items(), key=operator.itemgetter(1))
    return(sortedVector)

#keys, values = getKeyaValues(dummyList)
#print(vector(keys, values))

#mirnaVals = getKeyaValues(mirnaVars)
#print(mirnaVals)
#mirnaVector = vector(mirnaVals)
#print(mirnaVector)
#mrnaVals = getKeyaValues(mrnaVars)
#mrnaVector = vector(mrnaVals)
#protVals = getKeyaValues(protVars)
#protVector = vector(protVals)

#SAVE IN ARRAY FOR LATER

"""predictions[x] = predictionsRandomForest(dataset, workingSubset[:len(bestFeatures)+1])[0]
predictions[x] = predictionsLinearRegression(dataset, workingSubset[:len(bestFeatures)+1])[0]
predictions[x] = predictionsSVM(dataset, workingSubset[:len(bestFeatures)+1])[0]
predictions[x] = predictionsLASSO(dataset, workingSubset[:len(bestFeatures)+1])[0]
predictions[x] = predictionsGradientBoostingClassifier(dataset, workingSubset[:len(bestFeatures)+1])[0]
                
"""

# Boosting

In [ ]:
import xgboost as xgb
load_dataset('/Users/soniasharapova/Documents/MultiOmics/mirnaCategorical.csv', mirnaFeatures)
dtrain = xgb.DMatrix(data, label=label)

In [86]:
def bestFeats(dataset, feats, model):
    bestFeatures=[]
    bestPreds=[]
    remainingFeatures=copy.deepcopy(feats)
    workingSubset = np.empty((10)).astype(np.int32) #optimize over
    #predictions=np.empty((len(feats))).astype(np.int32)
    predictions=np.empty((len(feats)))
    
    while len(bestFeatures) < 10:
        for x in range(len(remainingFeatures)-1):
            #subset always includes best features, loop over remaining
            for y in range(len(bestFeatures)):
                workingSubset[y] = feats[bestFeatures[y]]
            
            workingSubset[len(bestFeatures)] = feats[remainingFeatures[x]]
            #workingSubset[len(bestFeatures)+1] = feats[-1]

            #print(workingSubset)
            if(model == 'RandomForest'):
                predictions[x]=predictionsRandomForest(dataset, workingSubset[:len(bestFeatures)+1])[0]
                #print('prediction',predictions[x])
            elif(model == 'LinearRegression'):
                predictions[x] = predictionsLinearRegression(dataset, workingSubset[:len(bestFeatures)+1])[0]
            elif(model == 'SVM'):
                predictions[x] = predictionsSVM(dataset, workingSubset[:len(bestFeatures)+1])[0]
            elif(model == 'LASSO'):
                predictions[x] = predictionsLASSO(dataset, workingSubset[:len(bestFeatures)+1])[0]
            elif(model == 'GradientBoostingClassifier'):
                predictions[x] = predictionsGradientBoostingClassifier(dataset, workingSubset[:len(bestFeatures)+1])[0]
                
            
        #smallest error is best
        
        #xx = predictions[:len(remainingFeatures)].argmax() #x corresponding to best x in remaining feature list
        minimum = predictions[:len(remainingFeatures)].argmin()
        xx = remainingFeatures[minimum]

        bestPreds.append(predictions[xx])
        #bestFeatures.append(remainingFeatures[xx])
        bestFeatures.append(remainingFeatures[xx])
        
        del remainingFeatures[xx]
        print('run', len(bestFeatures) + 1)
        
        #find location in feats
    
    ########
    
    print(bestFeatures)
    print(bestPreds)
       
    return bestFeatures, bestPreds

# KNN

In [32]:
#X = [[0], [1], [2], [3]]
#y = [0, 0, 1, 1]

from sklearn.neighbors import KNeighborsClassifier
datasetMirna = pd.read_csv('/Users/soniasharapova/Documents/MultiOmics/mirnaCategorical.csv')
labels = convertLabels(datasetMirna, mirnaFeatures)

datasetMirna = datasetMirna.loc[:, labels]

X = datasetMirna.iloc[:, :-1].values
y = datasetMirna.iloc[:, -1].values
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)




KNeighborsClassifier(n_neighbors=3)